# Generated by Django 4.2.16 on 2024-10-16 22:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre Completo')),
                ('pais', django_countries.fields.CountryField(max_length=2)),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('codigopostal', models.CharField(blank=True, max_length=12)),
                ('direccion_1', models.CharField(blank=True, max_length=150)),
                ('direccion_2', models.CharField(blank=True, max_length=150)),
                ('comuna', models.CharField(blank=True, max_length=150)),
                ('instrucciones_delivery', models.CharField(max_length=255, verbose_name='Instrucciones delivery')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='Creado en')),
                ('modificado_en', models.DateTimeField(auto_now_add=True, verbose_name='Modificado en')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'Direccion',
                'verbose_name_plural': 'Direcciones',
            },
        ),
    ]
