# Generated by Django 4.2.16 on 2024-10-25 16:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuentas', '0002_direccion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=250)),
                ('imagen_perfil', models.ImageField(default='media/default.jpg', null=True, upload_to='media')),
                ('direccion_user', models.TextField(max_length='50', null=True)),
                ('telefono', models.TextField(max_length=50, null=True)),
                ('tipo_trabajo', models.TextField(max_length=70, null=True)),
                ('cargo_trabajo', models.TextField(max_length=60)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
