# Generated by Django 4.2.16 on 2024-11-06 20:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='usuario_favoritos',
            field=models.ManyToManyField(blank=True, related_name='usuario_favoritos', to=settings.AUTH_USER_MODEL),
        ),
    ]
