# Generated by Django 4.2.16 on 2024-11-09 22:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0002_producto_usuario_favoritos'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForoProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='media/')),
                ('texto', models.TextField()),
                ('slug', models.SlugField(max_length=30)),
                ('subido_en', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('foro_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='principal.foroproducto')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('foro_producto', 'user')},
            },
        ),
        migrations.AddField(
            model_name='foroproducto',
            name='liike',
            field=models.ManyToManyField(related_name='productos_liked', through='principal.Like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='foroproducto',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='principal.producto'),
        ),
        migrations.AddField(
            model_name='foroproducto',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usuarios', to=settings.AUTH_USER_MODEL),
        ),
    ]
