# Generated by Django 4.2.16 on 2024-11-10 01:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_foroproducto_like_foroproducto_liike_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foroproducto',
            old_name='liike',
            new_name='like',
        ),
    ]
