# Generated by Django 4.2.16 on 2024-11-13 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_alter_like_unique_together_like_post_producto_liike_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='principal.comentario'),
        ),
    ]
