# Generated by Django 4.2.16 on 2024-11-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0007_publicacion'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
