# Generated by Django 4.2.16 on 2024-11-28 17:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('foro', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('principal', '0008_delete_publicacion'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='like',
            name='foro',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='foro.foro'),
        ),
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('post', 'foro', 'user')},
        ),
    ]
